include:
  - ./CASM/compose.yml
  - ./CSA/compose.yml
  - ./ISIM/compose.yaml
#  - ./Landing-Page/compose.yml # TODO add compose
#  - ./Network-Detection-Response/docker-compose.yml  # TODO: empty repo?
  - ./NSE/docker-compose.yml
  - ./SACD/compose.yaml
#  - ./WP6_AIBAST/docker-compose.yaml # Not needed for testing
